### PR TITLE
Fixes #36. NPM ignores .gitignore, so let's rename it when we copy it

### LINKED ISSUE #36: donejs init fails during execution
In can best be described by the following video:

https://asciinema.org/a/1wrkfvvexpfkoxeezohggdr9g

From @daffl in Slack -- For some very odd reason app/templates/.gitignore is named .npmignore in the installable generator-donejs

### PR DESCRIPTION
**Pull request by mjstahl**
I didn't do a string replace because I was concerned about replacing just a single `_` because it could create bugs in the future if we have files that contain underscores.

So I figured making it explicit as possible given the nature of the problem was best.

### CODE REVIEW

File: app/index.js [hunk 1]
```diff
@@ -171,9 +171,11 @@ module.exports = generators.Base.extend({
     }
 
     this.mainFiles.forEach(function(name) {
+      // Handle bug where npm has renamed .gitignore to .npmignore
+      // https://github.com/npm/npm/issues/3763
       self.fs.copyTpl(
         self.templatePath(name),
-        self.destinationPath(name),
+        self.destinationPath((name === "_gitignore") ? ".gitignore" : name),
```
Comment (daffl) [inline app/index.js]: Ah, this is only necessary for `.gitignore` right? All the other dotfiles should be included anyway.
